### ISSUE TITLE
Great work .! but import pnr status ? it throws error. where about the database.?

### ISSUE THREAD

**Issue by Rithika-Raj** [Hritik21/Railway-Support-Bot#1]

**Comment by Hritik21** [comment]
You will get them under "DBFILES" directory.

**Comment by Rithika-Raj** [comment]
yes. but still couldnt connect. : (   error: no module named pnrstatus. please provide more details on connecting to a database

**Comment by Hritik21** [comment]
You need to paste this files in a specific folder where the MySQL stores the Data in your system.
To get more clarification visit-
https://stackoverflow.com/questions/26402884/where-does-mysql-store-data
